version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx_server  # Цель сборки для Nginx и фронтенда
    ports:
      - "80:80"
    networks:
      - warehouse-network
    depends_on:
      - warehouse2

  warehouse2:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend  # Цель сборки для бэкенда
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=arangodb
      - DB_PORT=8529
    depends_on:
      - arangodb
    networks:
      - warehouse-network

  arangodb:
    image: arangodb:3.11.12
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=5DwY5BIAGFHpuSSE
      - ARANGO_ROOT_USERNAME=root
      - ARANGO_NO_AUTH=0
    networks:
      - warehouse-network
    volumes:
      - arango_data:/var/lib/arangodb3

networks:
  warehouse-network:
    driver: bridge

volumes:
  arango_data:
