# Стадия для сборки фронтенда (React)
FROM node:18 AS build_frontend
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY ./client/package*.json ./
RUN npm install

# Копируем все файлы фронтенда, включая папку public (где должен быть index.html)
COPY ./client/ ./
RUN npm run build

# Если хотите запускать frontend в своем контейнере, добавьте эту часть:
EXPOSE 3000
CMD ["npm", "start"]  



