version: '3.8'

services:
  frontend:
    build:
      context: .  # Контекст для фронтенда
      dockerfile: Dockerfile.frontend  # Указываем Dockerfile для фронтенда
    ports:
      - "3000:3000"
    networks:
      - warehouse-network

  warehouse2:
    build:
      context: .  # Контекст для бэкенда
      dockerfile: Dockerfile.backend  # Указываем Dockerfile для бэкенда
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=mongodb
      - DB_PORT=8529
    depends_on:
      - mongodb
    networks:
      - warehouse-network

  mongodb:
    image: mongo:latest
    ports:
      - "8529:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - warehouse-network
    volumes:
      - mongo_data:/data/db

networks:
  warehouse-network:
    driver: bridge

volumes:
  mongo_data:
