version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build_frontend  # Указываем целевой образ для фронтенда
    ports:
      - "3000:3000"
    networks:
      - warehouse-network

  warehouse2:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend  # Указываем целевой образ для бэкенда
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_HOST=arangodb
      - DB_PORT=8529
    depends_on:
      - arangodb
    networks:
      - warehouse-network

  arangodb:
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=5DwY5BIAGFHpuSSE
      - ARANGO_ROOT_USERNAME=root
      - ARANGO_NO_AUTH=0
    networks:
      - warehouse-network
    volumes:
      - arango_data:/var/lib/arangodb3

networks:
  warehouse-network:
    driver: bridge

volumes:
  arango_data:
