version: "3.8"

services:
  warehouse2:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: backend # Цель сборки для бэкенда
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DB_HOST=arangoDB
      - DB_PORT=8529
    depends_on:
      - arangodb
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      target: nginx_server # Цель сборки для Nginx и фронтенда
    restart: on-failure
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - warehouse2
    networks:
      - app-network

  arangodb:
    image: arangodb:3.12.3
    container_name: arangoDB
    hostname: arangoDB
    ports:
      - "8529:8529"
    environment:
      - ARANGO_ROOT_PASSWORD=5DwY5BIAGFHpuSSE
      - ARANGO_ROOT_USERNAME=root
      - ARANGO_NO_AUTH=1
    networks:
      - app-network
    volumes:
      - arango_data:/var/lib/arangodb3

networks:
  app-network:

volumes:
  arango_data:
